engtech-projects/MAC-loans

app/Http/Controllers/API/ReportsController.php, app/Models/Reports.php
Change output format of branch-insurance endpoint
add maturity report data
=> Reports branch maturity - insurance fix

resources/js/components/OverridePaymentView.vue, resources/js/ui/reports/repayment/Client.vue, resources/js/ui/transaction/override_payment/OverridePayment.vue
Override Payment Summary And View Modal Details
=> override_payment_summary and view button

app/Http/Controllers/API/BorrowerController.php, app/Http/Controllers/API/LoanAccountController.php, app/Http/Controllers/API/ReportsController.php, app/Http/Controllers/ReportsController.php, app/Http/Controllers/TransactionController.php, app/Models/Amortization.php, app/Models/Borrower.php, app/Models/LoanAccount.php, app/Models/Reports.php, config/enums.php, public/css/custom.css, resources/js/app.js, resources/js/components/AccountDetails.vue, resources/js/components/ClientListSide.vue, resources/js/ui/client_information/BalanceInquiry.vue, resources/js/ui/client_information/ClientList.vue, resources/js/ui/client_information/StatementDetails.vue, resources/js/ui/endofday/Endofday.vue, resources/js/ui/reports/MicroMonitoring.vue, resources/js/ui/reports/consolidated/GenerateDst.vue, resources/js/ui/transaction/override_payment/OverridePayment.vue, resources/js/ui/transaction/override_release/OverrideRelease.vue, resources/js/ui/transaction/rejected_release/RejectedRelease.vue, resources/js/ui/transaction/release_entry/ReleaseEntry.vue, resources/js/ui/transaction/repayment_entry/RepaymentDetailsNew.vue, resources/js/ui/transaction/repayment_entry/RepaymentEntryNew.vue, resources/views/reports/consolidated/generate_dst.blade.php, routes/web.php
- Fixed collection sheet
- Added delinquent,penalty,amount due columns
- Collection rate
=> Reports branch collection

app/Http/Controllers/API/BorrowerController.php, app/Http/Controllers/API/LoanAccountController.php, app/Http/Controllers/API/ReportsController.php, app/Http/Controllers/ReportsController.php, app/Http/Controllers/TransactionController.php, app/Models/Borrower.php, app/Models/Reports.php, config/enums.php, public/css/custom.css, resources/js/app.js, resources/js/components/AccountDetails.vue, resources/js/components/ClientListSide.vue, resources/js/ui/client_information/BalanceInquiry.vue, resources/js/ui/client_information/ClientList.vue, resources/js/ui/client_information/StatementDetails.vue, resources/js/ui/endofday/Endofday.vue, resources/js/ui/reports/MicroMonitoring.vue, resources/js/ui/reports/consolidated/GenerateDst.vue, resources/js/ui/transaction/override_payment/OverridePayment.vue, resources/js/ui/transaction/override_release/OverrideRelease.vue, resources/js/ui/transaction/rejected_release/RejectedRelease.vue, resources/js/ui/transaction/release_entry/ReleaseEntry.vue, resources/js/ui/transaction/repayment_entry/RepaymentDetailsNew.vue, resources/js/ui/transaction/repayment_entry/RepaymentEntryNew.vue, resources/views/reports/consolidated/generate_dst.blade.php, routes/web.php
=> Reports consolidated generate dst

app/Models/Reports.php, resources/js/ui/reports/branch/MaturityReport.vue
- Exclude paid accounts in maturity reports
- Add "ALL" text in maturity reports filter
=> Maturity reports

app/Models/LoanAccount.php, app/Models/Reports.php, resources/js/ui/reports/branch/AccountOfficer.vue
- FIXED (Delinquent Rate Incorrect formula)
- FIXED (Past Due Rate Incorrect formula)
- FIXED (Retrieve real time status)
=> Account officer performance reports

app/Http/Controllers/API/BorrowerController.php
(ADDED)
add specific columns for the borrower list query.
borrower_id
borrower_num
date_registered
firstname
middlename
lastname
suffix
address
birthdate
gender
status
contact_number
id_type
id_no
id_date_issued
spouse_firstname
spouse_middlename
spouse_lastname
spouse_address
spouse_birthdate
spouse_contact_number
spouse_id_type
spouse_id_no
spouse_id_date_issued
=> Borrower List (Adding Specific Columns)

app/Http/Controllers/API/CenterController.php, app/Models/Center.php
Sorting centers in Alphabetical order
=> FIXED - Centers sort in alphabetical order

app/Http/Controllers/API/BorrowerController.php, app/Http/Controllers/API/LoanAccountController.php, app/Http/Resources/LoanAccount.php, app/Models/Borrower.php, app/Models/EndTransaction.php, app/Models/LoanAccount.php, app/Models/Payment.php, resources/js/ui/transaction/repayment_entry/RepaymentDetails.vue, routes/api.php
Optimize selecting borrower
Optimize selecting loan account
=> Repayment entry optimization

app/Http/Controllers/API/LoanAccountController.php, app/Models/LoanAccount.php, resources/js/ui/transaction/release_entry/LoanDetails.vue, routes/api.php
Add new route in getting current amortization
=> ReleaseEntry Optimize

app/Models/LoanAccount.php
Select specific column in payment
=> Current Amortization

app/Models/LoanAccount.php
- Fixed payment status in loan account
- Fixed missed payment in loan account
=> Transaction(payment status update)

app/Models/LoanAccount.php, resources/js/ui/transaction/release_entry/LoanDetails.vue
-Fixed bug in retrieval of Rejected Loan Accounts in Rejected Release
-Fixed bug where no Loan Account ID is passed in Reference ID of Memo Payment
=> Transaction rejected release

app/Http/Controllers/API/LoanAccountController.php, app/Models/Document.php
[FIXED] Delete document data if the loan account deleted.
=> 376 document data delete document data in the backend when deleting a loan account

app/Http/Controllers/API/LoanAccountController.php, app/Http/Requests/UpdateCoMakerRequest.php, app/Models/LoanAccount.php, routes/api.php
Add
-route updatecomaker added
-function updateCoMaker added
-request updateCoMakerRequest added
=> Add route ability to edit co_maker information

queries/2.1 SELECT TranMast for loan_accounts.sql, queries/2.2 INSERT loan_accounts from tranmast.sql
Add loan status based in pdi and penalty from transmat table
-Fixed checking PDIBAL and PNLTYBAL for updating payment_status in insert,select queries
-Update column payment_status in query 2.2 INSERT loan_accounts from tranmast.sql
-Update column payment_status in query 2.1 SELECT TranMast for loan_accounts.sql
=> Modified insert/select queries

app/Http/Controllers/API/PaymentController.php, app/Http/Requests/UpdatePaymentRequest.php, routes/api.php
-Add route for updating payment details
-Add function in LoanAccountController for updating payment details
=> 385 ability to update payment details principal interest pdi penalty rebates total payment

app/Http/Controllers/API/LoanAccountController.php
Modify updateLoanAccount function
=> 386-ability-to-update-payment-status and loan-status

app/Http/Controllers/API/LoanAccountController.php, routes/api.php
Generate amortization for selected loan accounts
-Add route for generating the amortization schedule
-Add function in LoanAccountController for generating the amortization schedule
=> Generate Amortization

app/Http/Controllers/API/AmortizationController.php, app/Http/Controllers/API/LoanAccountController.php, routes/api.php
Add route fetching amortizations schedule
=> Fetch amortizations by loan accounts

app/Http/Controllers/API/AmortizationController.php, app/Models/Amortization.php
Update amortization schedule
Request validation added
=> Edit amortization

database/migrations/2023_04_04_030556_add_index_in_amortization_table.php, database/migrations/2023_04_04_030811_add_index_in_borrower_info_table.php, database/migrations/2023_04_04_030856_add_index_in_branch_table.php, database/migrations/2023_04_04_031046_add_index_in_loan_accounts_table.php, database/migrations/2023_04_04_031209_add_index_in_payment_table.php, database/migrations/2023_04_04_031351_add_index_in_product_table.php, database/migrations/2023_04_04_033006_add_index_in_users_table.php
Add index in selected columns in table
=> Table Indexing

app/Models/Reports.php
=> Branch Loan Listing Reports

resources/js/ui/client_information/StatementDetails.vue
Add loan status paid
Remove payment status past due
=> Add payment status

app/Models/Reports.php
Select only ongoing,pastdue and restructed loan status
=> Loan Listing fetch account

app/Models/Reports.php
=> Loan Listing

app/Http/Controllers/API/AmortizationController.php, routes/api.php
Route added for executing get current amortization for every loan account
=> get-current-amortization

resources/js/ui/transaction/override_payment/OverridePayment.vue
Fix bug in selecting all. All pages in paginations selected
=> Select all in transaction data fix

app/Http/Controllers/API/BorrowerController.php, app/Http/Resources/Borrower.php, app/Models/Borrower.php
Add borrower age depends on brithdate column
=> add borrower age

app/Models/Borrower.php
Sort loan accounts in decending order.
=> Sort loan accounts by date

app/Models/Reports.php
Exclude loan accounts with loan status restructed and res w/o pdi and balance is zero
=> Loanlisting fetch accounts update

app/Models/Reports.php
Fix fetching in account officer reports(Performace Reports)
=> Reports account officer fetching fix

app/Models/LoanAccount.php
=> Fix repayment entry penalty

app/Http/Controllers/API/LoanAccountController.php, app/Models/Document.php, app/Models/LoanAccount.php
- Generate Loan account number
- Generate Promissory number in document
=> FIX Loan account number and Promissory number generate

app/Models/LoanAccount.php
Change current amortization date to next amortization when amortization is paid for pension loan products
=> Pension Loan Fix

app/Models/Reports.php, resources/js/ui/reports/repayment/Client.vue
add amortization interest in fetching data
=> Reports repayment 

app/Http/Controllers/API/LoanAccountController.php, app/Models/Document.php, app/Models/LoanAccount.php
Fix generating account number duplicates.
=> Fix generating account number

app/Http/Controllers/API/LoanAccountController.php, app/Http/Controllers/API/PaymentController.php, app/Models/LoanAccount.php, app/Models/Payment.php, app/Models/Reports.php, resources/js/ui/transaction/repayment_entry/RepaymentDetails.vue, resources/js/ui/transaction/repayment_entry/RepaymentEntry.vue, routes/api.php
Fix issues page reload in repayment entry
=> Fix - Repayment Entry

composer.json, composer.lock, database/migrations/2023_07_14_090454_set_daysched_center_nullable.php, resources/js/ui/maintenance/CenterAccount.vue
-Fixed unable to deactivate center.
=> Updated Maintenance - Center

app/Http/Controllers/ClientInformationController.php, app/Http/Controllers/ClientPortalInformationController.php, app/Http/Controllers/EndOfDayController.php, app/Http/Controllers/MaintenanceController.php, app/Http/Controllers/ReportsController.php, app/Http/Controllers/TransactionController.php, resources/js/components/AccountDetails.vue, resources/js/ui/client_information/StatementDetails.vue, resources/js/ui/client_portal_information/StatementDetails.vue, resources/js/ui/transaction/override_payment/OverridePayment.vue, resources/js/ui/transaction/override_release/OverrideRelease.vue, resources/js/ui/transaction/override_release/OverrideReleaseDetails.vue, resources/js/ui/transaction/rejected_release/RejectedRelease.vue, resources/js/ui/transaction/release_entry/ReleaseEntry.vue, resources/js/ui/transaction/repayment_entry/RepaymentDetails.vue, resources/js/ui/transaction/repayment_entry/RepaymentDetailsNew.vue, resources/views/_layout/app.blade.php, resources/views/auth/borrower_login.blade.php, resources/views/auth/login.blade.php, resources/views/client_portal_layout/app.blade.php
- Changed format to Currency of Amount Loan and Interest (Release Entry, Repayment Entry, SOA, and Print SOA)
- Changed date format to MDY of Date Release and Due Date (Repayment Entry)
- Fixed Amortization Amount if loan type is Prepaid (excluding interest)
- Fixed Batch Override without loading screen (Override Release/Payment)
- Updated title of each landing page.
=> Additional Minor Fixes/Updates

app/Http/Controllers/API/PerformanceReportController.php, app/Http/Controllers/API/ReportsController.php, app/Models/Branch.php, app/Models/LoanAccount.php, app/Models/Payment.php, app/Models/PerformanceReport.php, app/Models/Reports.php, app/helper.php, resources/js/ui/reports/PerformanceReport.vue, resources/js/ui/transaction/repayment_entry/RepaymentDetails.vue, resources/views/reports/performance_report.blade.php, routes/api.php
- Added data ang functionality in Performance Report
=> Performance Report

app/Http/Controllers/API/ReportsController.php, app/Models/Reports.php
=> Report release - summary of loan release

composer.json, composer.lock, resources/js/components/DocumentsComponent.vue, resources/js/ui/client_information/StatementDetails.vue, resources/js/ui/client_portal_information/StatementDetails.vue, resources/js/ui/transaction/override_release/OverrideReleaseDetails.vue, resources/js/ui/transaction/release_entry/ReleaseEntry.vue
- Added borrower name in the content
- Update footer content
- Rearrange signed form.
=> Cash Voucher and Promissory Note Update content

resources/js/components/DocumentsComponent.vue, resources/js/ui/client_information/StatementDetails.vue, resources/js/ui/transaction/override_release/OverrideReleaseDetails.vue, resources/js/ui/transaction/release_entry/ReleaseEntry.vue, resources/views/transaction/rejected_release_edit.blade.php, resources/views/transaction/release_entry.blade.php
- Fixed Override Release due date changing when override is clicked
- Fixed Promissory Note header not center-aligned
- Fixed product object is shown instead of product name only
- Fixed Release Entry and Rejected Release Edit Promissory Note not showing the branch
=> Updated Promissory Note And Override Release Due Date

app/Http/Controllers/API/LoanAccountController.php
-Fixed issue where the amortization schedule was created multiple times due to repeated override button clicks on slow network responses.
=> Duplicate Amortization Fix

app/Http/Controllers/API/PaymentController.php, app/Models/Payment.php
-Applied multiple payments fix during payment creation instead of ongoing check
=> Reinforced Multiple Payments Fix

app/Http/Controllers/API/UserController.php, resources/js/ui/maintenance/UserSettings.vue
- Implemented a functionality to delete a user along with their accessibilities and branch assignments.
- Added automatic scrolling to the edit section when the edit button is clicked for better UX.
=> Implement user delete and scroll-to-edit improvement in User Settings

app/Http/Controllers/API/BaseController.php, app/Http/Controllers/API/DeductionController.php, app/Http/Controllers/API/LoanAccountController.php, app/Models/Deduction.php, resources/js/ui/maintenance/ActivityLogs.vue
-Activity transaction log fixed
=> Update incorrect transaction date in activity log
